const data = {
    korE : [
        "수소", "헬륨", "리튬", "베릴륨", "붕소", "탄소", "질소", "산소", "플루오린", "네온", "소듐(나트륨)", "마그네슘", "알루미늄", "규소", "인", "황", "염소", "아르곤", "포타슘(칼륨)", "칼슘"
    ],
    engE : [
        "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca"
    ],
    dic : {
        "treat" : "대하다",
        "diagnose" : "진단하다",
        "possess" : "지니다",
        "conformity" : "순응",
        "associate" : "관련시켜 생각하다",
        "overwhelm" : "압도하다",
        "devote" : "헌신하다",
        "persistence" : "끈기",
        "intend" : "의도하다",
        "detain" : "억류하다",
        "relevant" : "관련된",
        "portable" : "휴대용의",
        "measure" : "재다",
        "hesitate" : "주저하다",
        "include" : "포함하다",
        "enhance" : "향상시키다",
        "academic" : "학업의",
        "partly" : "부분적으로",
        "effectively" : "효과적으로",
        "overcome" : "극복하다",
        "neglect" : "등한시하다",
        "embrace" : "받아들이다",
        "celebrated" : "유명한",
        "advise" : "조언하다",
        "inward" : "안쪽으로",
        "invalid" : "효력 없는",
        "stimulate" : "자극하다",
        "mathematical" : "수학적인",
        "still" : "가만히 있는",
        "adjust" : "적응하다",
        "preferred" : "선호되는",
        "contaminate" : "오염시키다",
        "control" : "통제 집단",
        "vessel" : "그릇, 용기",
        "mythological" : "신화적인",
        "retell" : "다시 말하다",
        "means" : "수단",
        "motivate" : "동기를 부여하다",
        "unify" : "단결하다",
        "moral" : "도덕적인",
        "modesty" : "겸손",
        "heroic" : "영웅적인",
        "institution" : "단체",
        "socialization" : "사회화",
        "reinforce" : "강화시키다",
        "unite" : "결속시키다",
        "gratification" : "만족감",
        "whirring" : "윙윙거리는",
        "enthusiasm" : "열정",
        "favorable" : "유리한",
        "agony" : "괴로움",
        "lable" : "꼬리표를 붙이다",
        "continuous" : "지속적인",
        "improbable" : "있을 것 같지 않은",
        "predominate" : "지배하다",
        "retail" : "소매",
        "neutral" : "중립적인",
        "haunted" : "유령이 나오는",
        "stain" : "얼룩",
        "arrange" : "준비하다",
        "strict" : "엄격한",
        "estimate" : "가늠하다",
        "collection" : "소장품",
        "practicality" : "실용성",
        "support" : "후원",
        "scheme" : "계획",
        "surge" : "(갑자기) 밀려듦",
        "scatter" : "뿌리다",
        "imperative" : "필수적인",
        "impulsive" : "충동적인",
        "intermediate" : "중간의",
        "astray" : "길을 잃고",
        "novelist" : "소설가",
        "harness" : "(동력원 등으로) 이용하다",
        "misbehave" : "버릇없이 행동하다",
        "boom" : "호황기",
        "core" : "핵심적인",
        "desirable" : "바람직한",
        "utilize" : "이용하다",
        "annual" : "연례의"
    }
}
